drop table role if exists
drop table user if exists
drop table user_roles if exists
create table role (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, address varchar(255), email varchar(255), firstname varchar(255), full_name varchar(255), lastname varchar(255), password varchar(255), username varchar(255), primary key (id))
create table user_roles (users_id bigint not null, roles_id bigint not null, primary key (users_id, roles_id))
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK7ecyobaa59vxkxckg6t355l86 foreign key (users_id) references user